from setuptools import setup

setup(
    name="secml2",
    version="1.0",
    packages=[
        "secml2",
        "secml2.adv",
        "secml2.adv.evasion",
        "secml2.data",
        "secml2.models",
        "secml2.models.test",
        "secml2.models.pytorch",
        "secml2.models.pytorch.test",
        "secml2.models.sklearn",
        "secml2.models.sklearn.test",
        "secml2.models.tensorflow",
        "secml2.models.data_processing",
        "secml2.models.data_processing.test",
        "secml2.metrics",
        "secml2.metrics.test",
        "secml2.optimization",
        "secml2.manipulations",
    ],
    url="",
    license="",
    author="Maura Pintor, Luca Demetrio",
    author_email="",
    description="",
)
